In [32]:
# Step 1 : Import Libraries
import pandas as pd
import numpy as np

In [33]:
# Step 2: Load Datasets
df = pd.read_excel("Churn_Unclean_Project.xlsx")

In [34]:
# Step 3 : First Look
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 542 entries, 0 to 541
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            542 non-null    object
 1   Customer_Name          533 non-null    object
 2   Gender                 536 non-null    object
 3   Age                    536 non-null    float64
 4   State                  531 non-null    object
 5   City                   539 non-null    object
 6   Tenure_Months          534 non-null    float64
 7   Subscription_Type      530 non-null    object
 8   Monthly_Charges        529 non-null    float64
 9   Total_Charges          533 non-null    float64
 10  Contract_Type          538 non-null    object
 11  Payment_Method         526 non-null    object
 12  Internet_Service       535 non-null    object
 13  Tech_Support           530 non-null    object
 14  Senior_Citizen         534 non-null    object
 15  Dependents             539 non-null    object
 16  Churn                  538 non-null    object
 17  Last_Interaction_Date  539 non-null    object
dtypes: float64(4), object(14)
memory usage: 76.3+ KB

In [36]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  536.000000     534.000000       529.000000     533.000000
mean    44.399254      36.406367      1335.269206   49745.287336
std     18.556837      20.669599       715.972838   41644.111657
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       756.570000   18770.290000
50%     44.000000      38.000000      1306.800000   40649.600000
75%     57.000000      54.000000      1900.650000   75647.400000
max    165.000000      72.000000      2492.510000  171429.830000

In [37]:
df.shape

(542, 18)

In [38]:
# Step 4 : Check Missing Values 

df.isnull().sum()

Customer_ID               0
Customer_Name             9
Gender                    6
Age                       6
State                    11
City                      3
Tenure_Months             8
Subscription_Type        12
Monthly_Charges          13
Total_Charges             9
Contract_Type             4
Payment_Method           16
Internet_Service          7
Tech_Support             12
Senior_Citizen            8
Dependents                3
Churn                     4
Last_Interaction_Date     3
dtype: int64

In [39]:
# step 5 : check duplicates records 

df.duplicated().sum()

np.int64(7)

In [40]:
# Remove Duplicate 

df.drop_duplicates(inplace=True)

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
df.shape

(535, 18)

In [43]:
# Step 6 : Replace Dirty Values
df.replace(["N/A","NULL",""," "],np.nan,inplace=True)

In [44]:
df.isnull().sum()

Customer_ID               0
Customer_Name             8
Gender                    5
Age                       6
State                    10
City                      5
Tenure_Months             7
Subscription_Type        11
Monthly_Charges          12
Total_Charges             8
Contract_Type             3
Payment_Method           15
Internet_Service          6
Tech_Support             11
Senior_Citizen            7
Dependents                2
Churn                     3
Last_Interaction_Date     2
dtype: int64

In [47]:
df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Tenure_Months,Subscription_Type,Monthly_Charges,Total_Charges,Contract_Type,Payment_Method,Internet_Service,Tech_Support,Senior_Citizen,Dependents,Churn,Last_Interaction_Date
0,C1000,Abhishek Jaiswal,Female,35.0,Maharashtra,Pune,58.0,basic,1614.26,93273.08,One Year,UPI,Fiber,Yes,No,Yes,No,12-10-2025
1,C1001,Rohit Kumar,Male,NaN,Delhi,Noida,36.0,Premium,429.60,15858.60,Two Year,Cash,DSL,Yes,Yes,No,No,05-03-2026
2,C1002,Pooja Singh,Female,42.0,UP,Kanpur,13.0,Basic,555.03,6869.39,Month-to-Month,Debit Card,5G,No,No,No,Yes,20-02-2026
3,C1003,NaN,Male,59.0,Karnataka,Bengaluru,55.0,Standard,NaN,101349.10,Two Year,UPI,5G,No,No,Yes,No,07-06-2026
4,C1004,Mohit Arora,male,26.0,Gujarat,Ahmedabad,6.0,Premium,314.02,1926.12,One Year,Debit Card,Cable,Yes,No,No,No,02-04-2026

In [45]:
# Step 7 : Remove Extra Spaces 

df=df.apply(lambda x:x.str.strip() if x.dtype=="object" else x)

In [ ]:
# Value count 
df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Standard    169
Basic       167
basic         2
BASIC         2
Name: count, dtype: int64

In [ ]:
# Step 8 : Proper Case
df["Customer_Name"]=df["Customer_Name"].str.title()
df["State"]=df["State"].str.title()
df["City"]=df["City"].str.title()
df["Subscription_Type"]=df["Subscription_Type"].str.title()
df["Contract_Type"]=df["Contract_Type"].str.title()
df['Churn']=df['Churn'].str.title()
df["Gender"]=df["Gender"].str.title()
# df=df.apply(lambda x:x.str.title() if x.dtype=="object" else x)

In [52]:
df["Subscription_Type"].value_counts()

Subscription_Type
Premium     184
Basic       171
Standard    169
Name: count, dtype: int64

In [56]:
# Step 9 : Standardize Churn Column

df['Churn'].value_counts()

Churn
No     405
Yes    125
YES      1
yes      1
Name: count, dtype: int64

In [63]:
# Step 10 : Convert Numeric Columns
cols=["Age","Tenure_Months","Monthly_Charges","Total_Charges"]
for c in cols:
    df[c]=pd.to_numeric(df[c],errors="coerce")

In [64]:
df.describe()

              Age  Tenure_Months  Monthly_Charges  Total_Charges
count  529.000000     528.000000       523.000000     527.000000
mean    44.328922      36.518939      1329.967285   49739.683890
std     18.635396      20.659332       713.450173   41633.677902
min      3.000000       1.000000     -2454.770000  -99781.820000
25%     30.000000      19.000000       757.420000   18818.270000
50%     44.000000      38.000000      1295.880000   40649.600000
75%     57.000000      54.000000      1879.020000   75126.770000
max    165.000000      72.000000      2492.510000  171429.830000

In [ ]:
# Step 11 : Remove Invalid Age
    
df=df[(df["Age"]>=18)&(df["Age"]<=100)]

In [66]:
# Step 12 : Remove Negative Charges

df=df[df["Monthly_Charges"]>=0]
df=df[df["Total_Charges"]>=0]

In [68]:
df.shape

(492, 18)

In [ ]:
df["Last_Interaction_Date"]=pd.to_datetime(df["Last_Interaction_Date"],errors="coerce"
)